---

- name: Install dhcpd
  pkgng:
    name: "{{ dhcpd_openbsd_package }}"

- name: Create rc.d file
  template:
    src: FreeBSD.rcd.j2
    dest: /etc/rc.conf.d/dhcpd
    validate: sh -n %s

- name: Enable dhcpd
  service:
    name: "{{ dhcpd_openbsd_service }}"
    enabled: yes
