---
# tasks file for ansible-role-dhcpd-openbsd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ dhcpd-openbsd_log_dir }}"
    mode: 0755
    owner: "{{ dhcpd-openbsd_user }}"
    group: "{{ dhcpd-openbsd_group }}"
    state: directory
  notify: Restart dhcpd-openbsd

- name: Create db directory
  file:
    path: "{{ dhcpd-openbsd_db_dir }}"
    mode: 0755
    owner: "{{ dhcpd-openbsd_user }}"
    group: "{{ dhcpd-openbsd_group }}"
    state: directory
  notify: Restart dhcpd-openbsd

- name: Create dhcpd-openbsd.conf
  template:
    src: dhcpd-openbsd.conf.j2
    dest: "{{ dhcpd-openbsd_conf_file }}"
    validate: echo %s
  notify: Restart dhcpd-openbsd

- name: Start dhcpd-openbsd
  service:
    name: "{{ dhcpd-openbsd_service }}"
    enabled: true
    state: started
